//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KashanPayam
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    public partial class MessagesBL : KashanPayam.BaseBL
    {
        
        private long MsgIDField;
        
        private int UserIDField;
        
        private int LinkIDField;
        
        private int NumberIDField;
        
        private byte MsgTypeField;
        
        private string BodyField;
        
        private string UdhField;
        
        private System.DateTime SendDateField;
        
        private string SenderField;
        
        private string ReceiverField;
        
        private int FirstLocationField;
        
        private int CurrentLocationField;
        
        private int PartsField;
        
        private bool IsFlashField;
        
        private bool IsReadField;
        
        private bool IsUnicodeField;
        
        private double CreditField;
        
        private int ModuleField;
        
        private int RecCountField;
        
        private int RecFailedField;
        
        private int RecSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MsgID
        {
            get
            {
                return this.MsgIDField;
            }
            set
            {
                this.MsgIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LinkID
        {
            get
            {
                return this.LinkIDField;
            }
            set
            {
                this.LinkIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumberID
        {
            get
            {
                return this.NumberIDField;
            }
            set
            {
                this.NumberIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte MsgType
        {
            get
            {
                return this.MsgTypeField;
            }
            set
            {
                this.MsgTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Udh
        {
            get
            {
                return this.UdhField;
            }
            set
            {
                this.UdhField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int FirstLocation
        {
            get
            {
                return this.FirstLocationField;
            }
            set
            {
                this.FirstLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int CurrentLocation
        {
            get
            {
                return this.CurrentLocationField;
            }
            set
            {
                this.CurrentLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Parts
        {
            get
            {
                return this.PartsField;
            }
            set
            {
                this.PartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool IsFlash
        {
            get
            {
                return this.IsFlashField;
            }
            set
            {
                this.IsFlashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool IsUnicode
        {
            get
            {
                return this.IsUnicodeField;
            }
            set
            {
                this.IsUnicodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public double Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Module
        {
            get
            {
                return this.ModuleField;
            }
            set
            {
                this.ModuleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int RecCount
        {
            get
            {
                return this.RecCountField;
            }
            set
            {
                this.RecCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int RecFailed
        {
            get
            {
                return this.RecFailedField;
            }
            set
            {
                this.RecFailedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int RecSuccess
        {
            get
            {
                return this.RecSuccessField;
            }
            set
            {
                this.RecSuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KashanPayam.MessagesBL))]
    public partial class BaseBL : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodType", Namespace="http://tempuri.org/")]
    public enum PeriodType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Once = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yearly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    public class ArrayOfLong : System.Collections.Generic.List<long>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KashanPayam.SendSoap")]
    public interface SendSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.GetCreditResponse> GetCreditAsync(KashanPayam.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<byte> GetDeliveryAsync(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.UpdateDeliveryResponse> UpdateDeliveryAsync(KashanPayam.UpdateDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.GetInboxCountResponse> GetInboxCountAsync(KashanPayam.GetInboxCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.GetMessagesResponse> GetMessagesAsync(KashanPayam.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleSms", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.ScheduleSmsResponse> ScheduleSmsAsync(KashanPayam.ScheduleSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.SendSmsResponse> SendSmsAsync(KashanPayam.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsStringRec", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.SendSmsStringRecResponse> SendSmsStringRecAsync(KashanPayam.SendSmsStringRecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSVerify", ReplyAction="*")]
        System.Threading.Tasks.Task<KashanPayam.SendSMSVerifyResponse> SendSMSVerifyAsync(KashanPayam.SendSMSVerifyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetCreditRequestBody Body;
        
        public GetCreditRequest()
        {
        }
        
        public GetCreditRequest(KashanPayam.GetCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody()
        {
        }
        
        public GetCreditRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetCreditResponseBody Body;
        
        public GetCreditResponse()
        {
        }
        
        public GetCreditResponse(KashanPayam.GetCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody()
        {
        }
        
        public GetCreditResponseBody(double GetCreditResult)
        {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDelivery", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.UpdateDeliveryRequestBody Body;
        
        public UpdateDeliveryRequest()
        {
        }
        
        public UpdateDeliveryRequest(KashanPayam.UpdateDeliveryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDeliveryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RecID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public UpdateDeliveryRequestBody()
        {
        }
        
        public UpdateDeliveryRequestBody(long RecID, string username, string password)
        {
            this.RecID = RecID;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.UpdateDeliveryResponseBody Body;
        
        public UpdateDeliveryResponse()
        {
        }
        
        public UpdateDeliveryResponse(KashanPayam.UpdateDeliveryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDeliveryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateDeliveryResult;
        
        public UpdateDeliveryResponseBody()
        {
        }
        
        public UpdateDeliveryResponseBody(int UpdateDeliveryResult)
        {
            this.UpdateDeliveryResult = UpdateDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetInboxCountRequestBody Body;
        
        public GetInboxCountRequest()
        {
        }
        
        public GetInboxCountRequest(KashanPayam.GetInboxCountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isRead;
        
        public GetInboxCountRequestBody()
        {
        }
        
        public GetInboxCountRequestBody(string username, string password, bool isRead)
        {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetInboxCountResponseBody Body;
        
        public GetInboxCountResponse()
        {
        }
        
        public GetInboxCountResponse(KashanPayam.GetInboxCountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponseBody()
        {
        }
        
        public GetInboxCountResponseBody(int GetInboxCountResult)
        {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetMessagesRequestBody Body;
        
        public GetMessagesRequest()
        {
        }
        
        public GetMessagesRequest(KashanPayam.GetMessagesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public GetMessagesRequestBody()
        {
        }
        
        public GetMessagesRequestBody(string username, string password, int location, string from, int index, int count)
        {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.GetMessagesResponseBody Body;
        
        public GetMessagesResponse()
        {
        }
        
        public GetMessagesResponse(KashanPayam.GetMessagesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KashanPayam.MessagesBL[] GetMessagesResult;
        
        public GetMessagesResponseBody()
        {
        }
        
        public GetMessagesResponseBody(KashanPayam.MessagesBL[] GetMessagesResult)
        {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScheduleSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScheduleSms", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.ScheduleSmsRequestBody Body;
        
        public ScheduleSmsRequest()
        {
        }
        
        public ScheduleSmsRequest(KashanPayam.ScheduleSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScheduleSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime scheduleDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public KashanPayam.PeriodType period;
        
        public ScheduleSmsRequestBody()
        {
        }
        
        public ScheduleSmsRequestBody(string username, string password, string to, string from, string text, bool isflash, System.DateTime scheduleDateTime, KashanPayam.PeriodType period)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.scheduleDateTime = scheduleDateTime;
            this.period = period;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScheduleSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScheduleSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.ScheduleSmsResponseBody Body;
        
        public ScheduleSmsResponse()
        {
        }
        
        public ScheduleSmsResponse(KashanPayam.ScheduleSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScheduleSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ScheduleSmsResult;
        
        public ScheduleSmsResponseBody()
        {
        }
        
        public ScheduleSmsResponseBody(int ScheduleSmsResult)
        {
            this.ScheduleSmsResult = ScheduleSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSmsRequestBody Body;
        
        public SendSmsRequest()
        {
        }
        
        public SendSmsRequest(KashanPayam.SendSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KashanPayam.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] status;
        
        public SendSmsRequestBody()
        {
        }
        
        public SendSmsRequestBody(string username, string password, KashanPayam.ArrayOfString to, string from, string text, bool isflash, string udh, KashanPayam.ArrayOfLong recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSmsResponseBody Body;
        
        public SendSmsResponse()
        {
        }
        
        public SendSmsResponse(KashanPayam.SendSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSmsResponseBody()
        {
        }
        
        public SendSmsResponseBody(int SendSmsResult, KashanPayam.ArrayOfLong recId, byte[] status)
        {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsStringRecRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsStringRec", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSmsStringRecRequestBody Body;
        
        public SendSmsStringRecRequest()
        {
        }
        
        public SendSmsStringRecRequest(KashanPayam.SendSmsStringRecRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsStringRecRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KashanPayam.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public KashanPayam.ArrayOfString recIdstr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] status;
        
        public SendSmsStringRecRequestBody()
        {
        }
        
        public SendSmsStringRecRequestBody(string username, string password, KashanPayam.ArrayOfString to, string from, string text, bool isflash, string udh, KashanPayam.ArrayOfLong recId, KashanPayam.ArrayOfString recIdstr, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.recIdstr = recIdstr;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsStringRecResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsStringRecResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSmsStringRecResponseBody Body;
        
        public SendSmsStringRecResponse()
        {
        }
        
        public SendSmsStringRecResponse(KashanPayam.SendSmsStringRecResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsStringRecResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsStringRecResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KashanPayam.ArrayOfString recIdstr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] status;
        
        public SendSmsStringRecResponseBody()
        {
        }
        
        public SendSmsStringRecResponseBody(int SendSmsStringRecResult, KashanPayam.ArrayOfLong recId, KashanPayam.ArrayOfString recIdstr, byte[] status)
        {
            this.SendSmsStringRecResult = SendSmsStringRecResult;
            this.recId = recId;
            this.recIdstr = recIdstr;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSVerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSVerify", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSMSVerifyRequestBody Body;
        
        public SendSMSVerifyRequest()
        {
        }
        
        public SendSMSVerifyRequest(KashanPayam.SendSMSVerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSVerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public KashanPayam.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Parameter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int code;
        
        public SendSMSVerifyRequestBody()
        {
        }
        
        public SendSMSVerifyRequestBody(string username, string password, KashanPayam.ArrayOfString to, string Parameter, bool isflash, string udh, KashanPayam.ArrayOfLong recId, byte[] status, int code)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.Parameter = Parameter;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSVerifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSVerifyResponse", Namespace="http://tempuri.org/", Order=0)]
        public KashanPayam.SendSMSVerifyResponseBody Body;
        
        public SendSMSVerifyResponse()
        {
        }
        
        public SendSMSVerifyResponse(KashanPayam.SendSMSVerifyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSVerifyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSMSVerifyResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public KashanPayam.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSMSVerifyResponseBody()
        {
        }
        
        public SendSMSVerifyResponseBody(int SendSMSVerifyResult, KashanPayam.ArrayOfLong recId, byte[] status)
        {
            this.SendSMSVerifyResult = SendSMSVerifyResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SendSoapChannel : KashanPayam.SendSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<KashanPayam.SendSoap>, KashanPayam.SendSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), SendSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.GetCreditResponse> KashanPayam.SendSoap.GetCreditAsync(KashanPayam.GetCreditRequest request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.GetCreditResponse> GetCreditAsync(string username, string password)
        {
            KashanPayam.GetCreditRequest inValue = new KashanPayam.GetCreditRequest();
            inValue.Body = new KashanPayam.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KashanPayam.SendSoap)(this)).GetCreditAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<byte> GetDeliveryAsync(long recId)
        {
            return base.Channel.GetDeliveryAsync(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.UpdateDeliveryResponse> KashanPayam.SendSoap.UpdateDeliveryAsync(KashanPayam.UpdateDeliveryRequest request)
        {
            return base.Channel.UpdateDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.UpdateDeliveryResponse> UpdateDeliveryAsync(long RecID, string username, string password)
        {
            KashanPayam.UpdateDeliveryRequest inValue = new KashanPayam.UpdateDeliveryRequest();
            inValue.Body = new KashanPayam.UpdateDeliveryRequestBody();
            inValue.Body.RecID = RecID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KashanPayam.SendSoap)(this)).UpdateDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.GetInboxCountResponse> KashanPayam.SendSoap.GetInboxCountAsync(KashanPayam.GetInboxCountRequest request)
        {
            return base.Channel.GetInboxCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.GetInboxCountResponse> GetInboxCountAsync(string username, string password, bool isRead)
        {
            KashanPayam.GetInboxCountRequest inValue = new KashanPayam.GetInboxCountRequest();
            inValue.Body = new KashanPayam.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            return ((KashanPayam.SendSoap)(this)).GetInboxCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.GetMessagesResponse> KashanPayam.SendSoap.GetMessagesAsync(KashanPayam.GetMessagesRequest request)
        {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.GetMessagesResponse> GetMessagesAsync(string username, string password, int location, string from, int index, int count)
        {
            KashanPayam.GetMessagesRequest inValue = new KashanPayam.GetMessagesRequest();
            inValue.Body = new KashanPayam.GetMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            return ((KashanPayam.SendSoap)(this)).GetMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.ScheduleSmsResponse> KashanPayam.SendSoap.ScheduleSmsAsync(KashanPayam.ScheduleSmsRequest request)
        {
            return base.Channel.ScheduleSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.ScheduleSmsResponse> ScheduleSmsAsync(string username, string password, string to, string from, string text, bool isflash, System.DateTime scheduleDateTime, KashanPayam.PeriodType period)
        {
            KashanPayam.ScheduleSmsRequest inValue = new KashanPayam.ScheduleSmsRequest();
            inValue.Body = new KashanPayam.ScheduleSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.scheduleDateTime = scheduleDateTime;
            inValue.Body.period = period;
            return ((KashanPayam.SendSoap)(this)).ScheduleSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.SendSmsResponse> KashanPayam.SendSoap.SendSmsAsync(KashanPayam.SendSmsRequest request)
        {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.SendSmsResponse> SendSmsAsync(string username, string password, KashanPayam.ArrayOfString to, string from, string text, bool isflash, string udh, KashanPayam.ArrayOfLong recId, byte[] status)
        {
            KashanPayam.SendSmsRequest inValue = new KashanPayam.SendSmsRequest();
            inValue.Body = new KashanPayam.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            return ((KashanPayam.SendSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.SendSmsStringRecResponse> KashanPayam.SendSoap.SendSmsStringRecAsync(KashanPayam.SendSmsStringRecRequest request)
        {
            return base.Channel.SendSmsStringRecAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.SendSmsStringRecResponse> SendSmsStringRecAsync(string username, string password, KashanPayam.ArrayOfString to, string from, string text, bool isflash, string udh, KashanPayam.ArrayOfLong recId, KashanPayam.ArrayOfString recIdstr, byte[] status)
        {
            KashanPayam.SendSmsStringRecRequest inValue = new KashanPayam.SendSmsStringRecRequest();
            inValue.Body = new KashanPayam.SendSmsStringRecRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.recIdstr = recIdstr;
            inValue.Body.status = status;
            return ((KashanPayam.SendSoap)(this)).SendSmsStringRecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KashanPayam.SendSMSVerifyResponse> KashanPayam.SendSoap.SendSMSVerifyAsync(KashanPayam.SendSMSVerifyRequest request)
        {
            return base.Channel.SendSMSVerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<KashanPayam.SendSMSVerifyResponse> SendSMSVerifyAsync(string username, string password, KashanPayam.ArrayOfString to, string Parameter, bool isflash, string udh, KashanPayam.ArrayOfLong recId, byte[] status, int code)
        {
            KashanPayam.SendSMSVerifyRequest inValue = new KashanPayam.SendSMSVerifyRequest();
            inValue.Body = new KashanPayam.SendSMSVerifyRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.Parameter = Parameter;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            inValue.Body.code = code;
            return ((KashanPayam.SendSoap)(this)).SendSMSVerifyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://panel.kashanpayam.ir/post/send.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://panel.kashanpayam.ir/post/send.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendSoap,
            
            SendSoap12,
        }
    }
}
